# Generated by Django 3.1 on 2021-03-10 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('grupo', models.CharField(max_length=30, verbose_name='Grupo')),
                ('grado', models.IntegerField(blank=True, null=True, verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_esp', models.CharField(max_length=100, verbose_name='Nombre_Especialidad')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('grado', models.IntegerField(blank=True, null=True, verbose_name='Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('grado', models.IntegerField(blank=True, null=True, verbose_name='Grado')),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='tipoIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipoIncidencia',
                'verbose_name_plural': 'tipoIncidencias',
            },
        ),
        migrations.CreateModel(
            name='Problematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('solucion', models.CharField(max_length=120)),
                ('parcial', models.IntegerField(blank=True, null=True, verbose_name='Parcial')),
                ('semana', models.IntegerField(blank=True, null=True, verbose_name='Semana')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noAbandono.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noAbandono.materia')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noAbandono.tipoincidencia')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problematica',
                'verbose_name_plural': 'Problematicas',
            },
        ),
    ]
