# Generated by Django 3.1 on 2021-03-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noAbandono', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='grado',
        ),
    ]
