# Generated by Django 3.1 on 2021-03-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noAbandono', '0002_remove_alumno_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='grado',
        ),
        migrations.AddField(
            model_name='materia',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo'),
        ),
    ]
