# Generated by Django 3.1 on 2021-03-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noAbandono', '0003_auto_20210316_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
