# Generated by Django 3.1 on 2021-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noAbandono', '0005_auto_20210318_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='problematica',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo'),
        ),
    ]
