# Generated by Django 3.1 on 2021-03-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noAbandono', '0007_auto_20210322_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problematica',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noAbandono.grupo'),
        ),
    ]
