# Generated by Django 3.1 on 2021-03-23 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noAbandono', '0008_auto_20210322_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problematica',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha'),
        ),
    ]
