# Generated by Django 3.1 on 2021-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noAbandono', '0009_auto_20210323_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
